<h1 class="text-7xl text-center my-6 text-[#68e0ed] font-display pt-20">Web Accessibility</h1>

<div class="pl-50 pr-30">
    <div class="pb-20">
    <h1 class="text-3xl text-[#68e0ed] font-display pb-10"> Chapter 7: Reading Order</h1>
    <p class="text-xl font-displaytwo text-[#576566]">The concept of reading order is crucial to creating a usable and accessible web experience, especially for users who rely on screen readers. When we design websites, we often think about their visual layout, but we also need to consider how users access that content through other means. Screen readers, for example, read the page aloud to visually impaired users. These tools read the content in the order it appears in the HTML structure, so the reading order must follow a logical flow that makes sense.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">Websites are designed with a visual layout in mind, but it's important to remember that screen readers don’t "see" the page visually. Instead, they read the content in the order it appears in the HTML. For example, a navigation bar might be at the top of the page visually, but if the HTML has the footer listed before the main content, the footer would be read out of context, making the page harder to navigate for those using screen readers.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">To create an accessible experience, the HTML order must match the visual order. This means that the elements on the page, like headings, paragraphs, and interactive content, should be coded in a way that aligns with the logical progression of the page. If a form’s submit button is coded before the input fields, for instance, a screen reader user would encounter the button before they’ve even filled out the form.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">A common issue arises when web developers use CSS positioning (like absolute or fixed positioning) or JavaScript to visually rearrange content on the page. These techniques can affect the reading order, making the visual presentation different from what screen readers experience. Thus, it's important to ensure that the content is presented in a logical order within the HTML structure itself.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">Maintaining a correct reading order also means considering keyboard navigation. Keyboard-only users, like those with motor impairments, often rely on the Tab key to navigate interactive elements (links, buttons, form fields). Developers must ensure that the order in which elements are focused via the keyboard corresponds to the logical flow of the content.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">Ultimately, a properly structured reading order ensures that users—whether they're using a screen reader, keyboard, or other assistive tools—can navigate your website in a way that makes sense. Thoughtfully organizing content helps prevent confusion and makes the web more accessible to everyone.</p>
</div>
</div>