<h1 class="text-7xl text-center my-6 text-[#68e0ed] font-display pt-20">Web Accessibility</h1>

<div class="pl-50 pr-30">
    <div class="pb-20">
    <h1 class="text-3xl text-[#68e0ed] font-display pb-10"> Chapter 1: What is Accessibility?</h1>
    <p class="text-xl font-displaytwo text-[#576566]">Accessibility on the web refers to the practice of designing websites and applications so that people, regardless of their physical, sensory, or cognitive abilities, can use them effectively. The web should be a space that everyone can access and navigate, including individuals with disabilities.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">The key idea behind accessibility is inclusion. When we create websites that are accessible, we ensure that all people, regardless of their abilities, can understand, navigate, and interact with content. Disabilities can vary widely—ranging from visual impairments like blindness or low vision to hearing impairments, motor difficulties, or cognitive challenges. Accessibility is not just about accommodating those with permanent disabilities but also about considering temporary conditions, like a person with a broken arm or someone who’s trying to interact with a website in a noisy environment.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">One of the most common misconceptions is that accessibility only benefits users with disabilities. In reality, accessibility improves the user experience for everyone. For instance, better contrast between text and backgrounds helps people with visual impairments, but it also benefits anyone reading on a dimly lit screen. Simplified navigation and clearer instructions help people with cognitive disabilities, but they can also improve usability for anyone who finds the design more intuitive and easy to follow.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">In this context, assistive technologies like screen readers, text-to-speech software, or alternative input devices are essential tools for some users. However, the goal is not just to accommodate these technologies but to design websites that work well for all users, whether or not they rely on assistive tools. Websites should provide content that is usable by all, and this often means thinking about the user’s needs from the very beginning of the design process.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">To ensure websites meet accessibility needs, developers and designers follow guidelines known as WCAG (Web Content Accessibility Guidelines). These guidelines are built around four main principles: Perceivable, Operable, Understandable, and Robust, which help create websites that provide a solid foundation for accessibility.</p>
    <ul class="text-xl font-displaytwo text-[#576566] pt-8 pl-10 list-disc">
        <li>Perceivable means that users must be able to perceive the information on the page, whether it’s through text, images, or multimedia. For example, images should have text descriptions (alt text) so that screen readers can convey the same information to someone who is visually impaired.</li>
        <li>Operable refers to making sure users can interact with the website, especially without relying on a mouse. This means ensuring that navigation and interactive elements are usable through the keyboard or other alternative input methods.</li>
        <li>Understandable ensures that the content is clear and easy to comprehend. This includes using simple language, offering clear instructions, and ensuring that the site’s design doesn’t confuse users.</li>
        <li>Robust refers to ensuring that the website works well with current and future technologies. It’s important that the site remains accessible as new browsers, devices, and assistive technologies emerge.</li>
    </ul>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">In short, accessibility is about designing inclusively, ensuring that anyone can access and interact with web content regardless of their abilities or situation. It’s not just a technical requirement—it’s a fundamental principle that empowers individuals, fosters equality, and helps create a more inclusive digital world.</p>
</div>
</div>