<h1 class="text-7xl text-center my-6 text-[#68e0ed] font-display pt-20">Web Accessibility</h1>

<div class="pl-50 pr-30">
    <div class="pb-20">
    <h1 class="text-3xl text-[#68e0ed] font-display pb-10"> Chapter 9: Responsive Design</h1>
    <p class="text-xl font-displaytwo text-[#576566]">Chapter 9: Responsive Design explores how making websites adaptable to different screen sizes and devices also improves accessibility. While responsive design is often associated with making websites mobile-friendly, its role in accessibility goes deeper—it ensures content is usable by people with various needs, including those who rely on assistive technologies or have visual and motor impairments.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">A responsive website adjusts its layout and content based on the user’s screen size, orientation, and resolution. This adaptability benefits users who zoom in to see content more clearly, use screen magnifiers, or navigate on small devices. Without responsive design, zooming in might cause elements to overlap or be cut off, making the site hard to use for people who need enlarged text or visuals.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">For users with limited mobility, responsive design can also make it easier to interact with content. Larger touch targets on mobile devices, for example, are more accessible for users who have difficulty with precise movements. If buttons or links are too small or placed too close together, users may struggle to tap them, especially if they use assistive tools like mouth sticks or screen readers with touch gestures.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">Responsiveness also helps people who adjust settings to meet their needs, such as increasing font size or using custom style sheets. A well-designed site should handle these changes without breaking the layout. If the content overflows or becomes unreadable after a user increases text size, that’s a sign the design isn’t truly accessible.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">It’s also important to make sure interactive elements remain functional at all screen sizes. Navigation menus, forms, and buttons should remain easy to access whether the user is on a desktop computer or a mobile phone. Techniques like collapsible menus, fluid grids, and scalable images help maintain usability without sacrificing accessibility.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">Responsive design benefits users in temporary or situational contexts, too—someone using one hand while holding a baby, or reading a screen in harsh sunlight, for example. These scenarios, while not permanent disabilities, still demand a flexible and forgiving design approach that works under a variety of conditions.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">In short, accessibility and responsive design go hand-in-hand. By making layouts adaptable, text readable at any size, and interactions easy across all devices, developers support a broader, more inclusive audience. Accessibility isn’t just about supporting assistive tech—it’s about making the web work for everyone, in every situation.</p>
</div>
</div>