<h1 class="text-7xl text-center my-6 text-[#68e0ed] font-display pt-20">Web Accessibility</h1>

<div class="pl-50 pr-30">
    <div class="pb-20">
    <h1 class="text-3xl text-[#68e0ed] font-display pb-10"> Chapter 8: Contrast</h1>
    <p class="text-xl font-displaytwo text-[#576566]">Chapter 8: Contrast focuses on the importance of ensuring there’s sufficient contrast between text and its background to make content readable for everyone, especially those with visual impairments. For people with low vision or color blindness, poor contrast can make text difficult to read, but even people with no visual impairments can benefit from high contrast in certain conditions, like bright sunlight or when viewing on a small screen.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">The Web Content Accessibility Guidelines (WCAG) recommend a contrast ratio of at least 4.5:1 for normal text and 3:1 for larger text (18pt or 14pt bold and above). This ensures that the text stands out against its background, making it more legible. Without sufficient contrast, text may appear faint or indistinct, which can hinder readability for many users, particularly those with aging eyesight or color blindness.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">Contrast isn’t just about black text on a white background. Color combinations such as light gray on white or green on light yellow might look fine to some users but can be nearly invisible to others. This is why it's crucial to use tools that test contrast ratios and help identify combinations that fall below the recommended thresholds.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">To test contrast, developers can use various online tools and browser extensions that check the contrast ratio between text and background colors. These tools can help ensure that the text is readable for users with a variety of visual impairments, including those who are color blind or have low vision. For example, combinations like red text on green background might be problematic for users with red-green color blindness.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">Improving contrast is a simple but effective way to make a website more accessible. High contrast can also improve readability in different lighting conditions, like when someone is outdoors or using a device with a bright display. It’s a best practice to use contrasting colors to highlight interactive elements, like links and buttons, so users can easily identify where to click or tap.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">In addition to text, contrast is also important for other visual elements, such as icons and buttons. Icons and graphics should be clearly visible and distinguishable from the background to make them easier to recognize for users with visual impairments. For example, a gray button on a light gray background would be hard to spot and use, so ensuring enough contrast can make these elements more intuitive and accessible.</p>
    <p class="text-xl font-displaytwo text-[#576566] pt-8">Ultimately, making sure that text and elements have sufficient contrast is one of the easiest and most impactful ways to enhance accessibility. By adhering to contrast guidelines, developers ensure that their websites are usable for a larger audience, including people with visual disabilities, and improve the overall user experience for everyone.</p>
</div>
</div>